[debug] [2021-04-19T15:20:35.901Z] ----------------------------------------------------------------------
[debug] [2021-04-19T15:20:35.903Z] Command:       C:\Program Files\nodejs\node.exe C:\Users\otter\AppData\Roaming\npm\node_modules\firebase-tools\lib\bin\firebase.js update
[debug] [2021-04-19T15:20:35.904Z] CLI Version:   7.10.0
[debug] [2021-04-19T15:20:35.904Z] Platform:      win32
[debug] [2021-04-19T15:20:35.904Z] Node Version:  v15.14.0
[debug] [2021-04-19T15:20:35.906Z] Time:          Mon Apr 19 2021 11:20:35 GMT-0400 (Eastern Daylight Time)
[debug] [2021-04-19T15:20:35.906Z] ----------------------------------------------------------------------
[debug] [2021-04-19T15:20:35.906Z] 
[error] Error: [object Object] is not a Firebase command
[debug] [2021-04-19T15:20:35.916Z] TypeError: str.toLowerCase is not a function
    at didYouMean (C:\Users\otter\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\didyoumean\didYouMean-1.2.1.js:147:48)
    at suggestCommands (C:\Users\otter\AppData\Roaming\npm\node_modules\firebase-tools\lib\index.js:28:22)
    at Command.<anonymous> (C:\Users\otter\AppData\Roaming\npm\node_modules\firebase-tools\lib\index.js:57:14)
    at Command.listener (C:\Users\otter\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\commander\index.js:360:8)
    at Command.emit (node:events:369:20)
    at Command.emit (node:domain:470:12)
    at Command.parseArgs (C:\Users\otter\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\commander\index.js:801:12)
    at Command.parse (C:\Users\otter\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\commander\index.js:563:21)
    at Object.<anonymous> (C:\Users\otter\AppData\Roaming\npm\node_modules\firebase-tools\lib\bin\firebase.js:98:22)
    at Module._compile (node:internal/modules/cjs/loader:1092:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1121:10)
    at Module.load (node:internal/modules/cjs/loader:972:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)
    at node:internal/main/run_main_module:17:47
[error] 
[error] Error: An unexpected error has occurred.
